/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedCreatorsRouteImport } from './routes/_authenticated/creators'
import { Route as AuthenticatedVIdRouteImport } from './routes/_authenticated/v.$id'
import { Route as AuthenticatedMeTabRouteImport } from './routes/_authenticated/me.$tab'
import { Route as AuthenticatedLeaderboardArchiveRouteImport } from './routes/_authenticated/leaderboard.archive'
import { Route as AuthenticatedCreatorsIdRouteImport } from './routes/_authenticated/creators.$id'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminRecommendationsRouteImport } from './routes/_authenticated/admin.recommendations'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as ApiPublicCronLeaderboardRouteImport } from './routes/api/public/cron/leaderboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreatorsRoute = AuthenticatedCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVIdRoute = AuthenticatedVIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeTabRoute = AuthenticatedMeTabRouteImport.update({
  id: '/me/$tab',
  path: '/me/$tab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardArchiveRoute =
  AuthenticatedLeaderboardArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedLeaderboardRoute,
  } as any)
const AuthenticatedCreatorsIdRoute = AuthenticatedCreatorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCreatorsRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRecommendationsRoute =
  AuthenticatedAdminRecommendationsRouteImport.update({
    id: '/admin/recommendations',
    path: '/admin/recommendations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicCronLeaderboardRoute =
  ApiPublicCronLeaderboardRouteImport.update({
    id: '/api/public/cron/leaderboard',
    path: '/api/public/cron/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/creators': typeof AuthenticatedCreatorsRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/leaderboard/archive': typeof AuthenticatedLeaderboardArchiveRoute
  '/me/$tab': typeof AuthenticatedMeTabRoute
  '/v/$id': typeof AuthenticatedVIdRoute
  '/api/public/cron/leaderboard': typeof ApiPublicCronLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/creators': typeof AuthenticatedCreatorsRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/leaderboard/archive': typeof AuthenticatedLeaderboardArchiveRoute
  '/me/$tab': typeof AuthenticatedMeTabRoute
  '/v/$id': typeof AuthenticatedVIdRoute
  '/api/public/cron/leaderboard': typeof ApiPublicCronLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/creators': typeof AuthenticatedCreatorsRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/_authenticated/leaderboard/archive': typeof AuthenticatedLeaderboardArchiveRoute
  '/_authenticated/me/$tab': typeof AuthenticatedMeTabRoute
  '/_authenticated/v/$id': typeof AuthenticatedVIdRoute
  '/api/public/cron/leaderboard': typeof ApiPublicCronLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/creators'
    | '/feed'
    | '/leaderboard'
    | '/moderation'
    | '/admin/audit'
    | '/admin/recommendations'
    | '/admin/roles'
    | '/creators/$id'
    | '/leaderboard/archive'
    | '/me/$tab'
    | '/v/$id'
    | '/api/public/cron/leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/creators'
    | '/feed'
    | '/leaderboard'
    | '/moderation'
    | '/admin/audit'
    | '/admin/recommendations'
    | '/admin/roles'
    | '/creators/$id'
    | '/leaderboard/archive'
    | '/me/$tab'
    | '/v/$id'
    | '/api/public/cron/leaderboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/creators'
    | '/_authenticated/feed'
    | '/_authenticated/leaderboard'
    | '/_authenticated/moderation'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/recommendations'
    | '/_authenticated/admin/roles'
    | '/_authenticated/creators/$id'
    | '/_authenticated/leaderboard/archive'
    | '/_authenticated/me/$tab'
    | '/_authenticated/v/$id'
    | '/api/public/cron/leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronLeaderboardRoute: typeof ApiPublicCronLeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creators': {
      id: '/_authenticated/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof AuthenticatedCreatorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/v/$id': {
      id: '/_authenticated/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof AuthenticatedVIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/$tab': {
      id: '/_authenticated/me/$tab'
      path: '/me/$tab'
      fullPath: '/me/$tab'
      preLoaderRoute: typeof AuthenticatedMeTabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard/archive': {
      id: '/_authenticated/leaderboard/archive'
      path: '/archive'
      fullPath: '/leaderboard/archive'
      preLoaderRoute: typeof AuthenticatedLeaderboardArchiveRouteImport
      parentRoute: typeof AuthenticatedLeaderboardRoute
    }
    '/_authenticated/creators/$id': {
      id: '/_authenticated/creators/$id'
      path: '/$id'
      fullPath: '/creators/$id'
      preLoaderRoute: typeof AuthenticatedCreatorsIdRouteImport
      parentRoute: typeof AuthenticatedCreatorsRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/recommendations': {
      id: '/_authenticated/admin/recommendations'
      path: '/admin/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AuthenticatedAdminRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron/leaderboard': {
      id: '/api/public/cron/leaderboard'
      path: '/api/public/cron/leaderboard'
      fullPath: '/api/public/cron/leaderboard'
      preLoaderRoute: typeof ApiPublicCronLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCreatorsRouteChildren {
  AuthenticatedCreatorsIdRoute: typeof AuthenticatedCreatorsIdRoute
}

const AuthenticatedCreatorsRouteChildren: AuthenticatedCreatorsRouteChildren = {
  AuthenticatedCreatorsIdRoute: AuthenticatedCreatorsIdRoute,
}

const AuthenticatedCreatorsRouteWithChildren =
  AuthenticatedCreatorsRoute._addFileChildren(
    AuthenticatedCreatorsRouteChildren,
  )

interface AuthenticatedLeaderboardRouteChildren {
  AuthenticatedLeaderboardArchiveRoute: typeof AuthenticatedLeaderboardArchiveRoute
}

const AuthenticatedLeaderboardRouteChildren: AuthenticatedLeaderboardRouteChildren =
  {
    AuthenticatedLeaderboardArchiveRoute: AuthenticatedLeaderboardArchiveRoute,
  }

const AuthenticatedLeaderboardRouteWithChildren =
  AuthenticatedLeaderboardRoute._addFileChildren(
    AuthenticatedLeaderboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCreatorsRoute: typeof AuthenticatedCreatorsRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRouteWithChildren
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminRecommendationsRoute: typeof AuthenticatedAdminRecommendationsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedMeTabRoute: typeof AuthenticatedMeTabRoute
  AuthenticatedVIdRoute: typeof AuthenticatedVIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreatorsRoute: AuthenticatedCreatorsRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRouteWithChildren,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminRecommendationsRoute:
    AuthenticatedAdminRecommendationsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedMeTabRoute: AuthenticatedMeTabRoute,
  AuthenticatedVIdRoute: AuthenticatedVIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronLeaderboardRoute: ApiPublicCronLeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
