/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrendingRouteImport } from './routes/_authenticated/trending'
import { Route as AuthenticatedSuggestRouteImport } from './routes/_authenticated/suggest'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCreatorsIndexRouteImport } from './routes/_authenticated/creators.index'
import { Route as AuthenticatedVIdRouteImport } from './routes/_authenticated/v.$id'
import { Route as AuthenticatedMeTabRouteImport } from './routes/_authenticated/me.$tab'
import { Route as AuthenticatedLeaderboardArchiveRouteImport } from './routes/_authenticated/leaderboard.archive'
import { Route as AuthenticatedCreatorsIdRouteImport } from './routes/_authenticated/creators.$id'
import { Route as AuthenticatedCategoriesSlugRouteImport } from './routes/_authenticated/categories.$slug'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminRecommendationsRouteImport } from './routes/_authenticated/admin.recommendations'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin.broadcast'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as ApiPublicCronSessionExpiryWarnRouteImport } from './routes/api/public/cron/session-expiry-warn'
import { Route as ApiPublicCronRefreshMvsRouteImport } from './routes/api/public/cron/refresh-mvs'
import { Route as ApiPublicCronLeaderboardRouteImport } from './routes/api/public/cron/leaderboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrendingRoute = AuthenticatedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuggestRoute = AuthenticatedSuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreatorsIndexRoute =
  AuthenticatedCreatorsIndexRouteImport.update({
    id: '/creators/',
    path: '/creators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVIdRoute = AuthenticatedVIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeTabRoute = AuthenticatedMeTabRouteImport.update({
  id: '/me/$tab',
  path: '/me/$tab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardArchiveRoute =
  AuthenticatedLeaderboardArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedLeaderboardRoute,
  } as any)
const AuthenticatedCreatorsIdRoute = AuthenticatedCreatorsIdRouteImport.update({
  id: '/creators/$id',
  path: '/creators/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesSlugRoute =
  AuthenticatedCategoriesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCategoriesRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRecommendationsRoute =
  AuthenticatedAdminRecommendationsRouteImport.update({
    id: '/admin/recommendations',
    path: '/admin/recommendations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/admin/broadcast',
    path: '/admin/broadcast',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicCronSessionExpiryWarnRoute =
  ApiPublicCronSessionExpiryWarnRouteImport.update({
    id: '/api/public/cron/session-expiry-warn',
    path: '/api/public/cron/session-expiry-warn',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshMvsRoute = ApiPublicCronRefreshMvsRouteImport.update({
  id: '/api/public/cron/refresh-mvs',
  path: '/api/public/cron/refresh-mvs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronLeaderboardRoute =
  ApiPublicCronLeaderboardRouteImport.update({
    id: '/api/public/cron/leaderboard',
    path: '/api/public/cron/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/categories': typeof AuthenticatedCategoriesRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/suggest': typeof AuthenticatedSuggestRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/leaderboard/archive': typeof AuthenticatedLeaderboardArchiveRoute
  '/me/$tab': typeof AuthenticatedMeTabRoute
  '/v/$id': typeof AuthenticatedVIdRoute
  '/creators/': typeof AuthenticatedCreatorsIndexRoute
  '/api/public/cron/leaderboard': typeof ApiPublicCronLeaderboardRoute
  '/api/public/cron/refresh-mvs': typeof ApiPublicCronRefreshMvsRoute
  '/api/public/cron/session-expiry-warn': typeof ApiPublicCronSessionExpiryWarnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/categories': typeof AuthenticatedCategoriesRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/suggest': typeof AuthenticatedSuggestRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/leaderboard/archive': typeof AuthenticatedLeaderboardArchiveRoute
  '/me/$tab': typeof AuthenticatedMeTabRoute
  '/v/$id': typeof AuthenticatedVIdRoute
  '/creators': typeof AuthenticatedCreatorsIndexRoute
  '/api/public/cron/leaderboard': typeof ApiPublicCronLeaderboardRoute
  '/api/public/cron/refresh-mvs': typeof ApiPublicCronRefreshMvsRoute
  '/api/public/cron/session-expiry-warn': typeof ApiPublicCronSessionExpiryWarnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/suggest': typeof AuthenticatedSuggestRoute
  '/_authenticated/trending': typeof AuthenticatedTrendingRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/_authenticated/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/_authenticated/leaderboard/archive': typeof AuthenticatedLeaderboardArchiveRoute
  '/_authenticated/me/$tab': typeof AuthenticatedMeTabRoute
  '/_authenticated/v/$id': typeof AuthenticatedVIdRoute
  '/_authenticated/creators/': typeof AuthenticatedCreatorsIndexRoute
  '/api/public/cron/leaderboard': typeof ApiPublicCronLeaderboardRoute
  '/api/public/cron/refresh-mvs': typeof ApiPublicCronRefreshMvsRoute
  '/api/public/cron/session-expiry-warn': typeof ApiPublicCronSessionExpiryWarnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/categories'
    | '/feed'
    | '/leaderboard'
    | '/moderation'
    | '/suggest'
    | '/trending'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/categories/$slug'
    | '/creators/$id'
    | '/leaderboard/archive'
    | '/me/$tab'
    | '/v/$id'
    | '/creators/'
    | '/api/public/cron/leaderboard'
    | '/api/public/cron/refresh-mvs'
    | '/api/public/cron/session-expiry-warn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/categories'
    | '/feed'
    | '/leaderboard'
    | '/moderation'
    | '/suggest'
    | '/trending'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/categories/$slug'
    | '/creators/$id'
    | '/leaderboard/archive'
    | '/me/$tab'
    | '/v/$id'
    | '/creators'
    | '/api/public/cron/leaderboard'
    | '/api/public/cron/refresh-mvs'
    | '/api/public/cron/session-expiry-warn'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/categories'
    | '/_authenticated/feed'
    | '/_authenticated/leaderboard'
    | '/_authenticated/moderation'
    | '/_authenticated/suggest'
    | '/_authenticated/trending'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/recommendations'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/categories/$slug'
    | '/_authenticated/creators/$id'
    | '/_authenticated/leaderboard/archive'
    | '/_authenticated/me/$tab'
    | '/_authenticated/v/$id'
    | '/_authenticated/creators/'
    | '/api/public/cron/leaderboard'
    | '/api/public/cron/refresh-mvs'
    | '/api/public/cron/session-expiry-warn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronLeaderboardRoute: typeof ApiPublicCronLeaderboardRoute
  ApiPublicCronRefreshMvsRoute: typeof ApiPublicCronRefreshMvsRoute
  ApiPublicCronSessionExpiryWarnRoute: typeof ApiPublicCronSessionExpiryWarnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trending': {
      id: '/_authenticated/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthenticatedTrendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suggest': {
      id: '/_authenticated/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof AuthenticatedSuggestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creators/': {
      id: '/_authenticated/creators/'
      path: '/creators'
      fullPath: '/creators/'
      preLoaderRoute: typeof AuthenticatedCreatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/v/$id': {
      id: '/_authenticated/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof AuthenticatedVIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/$tab': {
      id: '/_authenticated/me/$tab'
      path: '/me/$tab'
      fullPath: '/me/$tab'
      preLoaderRoute: typeof AuthenticatedMeTabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard/archive': {
      id: '/_authenticated/leaderboard/archive'
      path: '/archive'
      fullPath: '/leaderboard/archive'
      preLoaderRoute: typeof AuthenticatedLeaderboardArchiveRouteImport
      parentRoute: typeof AuthenticatedLeaderboardRoute
    }
    '/_authenticated/creators/$id': {
      id: '/_authenticated/creators/$id'
      path: '/creators/$id'
      fullPath: '/creators/$id'
      preLoaderRoute: typeof AuthenticatedCreatorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/$slug': {
      id: '/_authenticated/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof AuthenticatedCategoriesSlugRouteImport
      parentRoute: typeof AuthenticatedCategoriesRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/recommendations': {
      id: '/_authenticated/admin/recommendations'
      path: '/admin/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AuthenticatedAdminRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/admin/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron/session-expiry-warn': {
      id: '/api/public/cron/session-expiry-warn'
      path: '/api/public/cron/session-expiry-warn'
      fullPath: '/api/public/cron/session-expiry-warn'
      preLoaderRoute: typeof ApiPublicCronSessionExpiryWarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-mvs': {
      id: '/api/public/cron/refresh-mvs'
      path: '/api/public/cron/refresh-mvs'
      fullPath: '/api/public/cron/refresh-mvs'
      preLoaderRoute: typeof ApiPublicCronRefreshMvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/leaderboard': {
      id: '/api/public/cron/leaderboard'
      path: '/api/public/cron/leaderboard'
      fullPath: '/api/public/cron/leaderboard'
      preLoaderRoute: typeof ApiPublicCronLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCategoriesRouteChildren {
  AuthenticatedCategoriesSlugRoute: typeof AuthenticatedCategoriesSlugRoute
}

const AuthenticatedCategoriesRouteChildren: AuthenticatedCategoriesRouteChildren =
  {
    AuthenticatedCategoriesSlugRoute: AuthenticatedCategoriesSlugRoute,
  }

const AuthenticatedCategoriesRouteWithChildren =
  AuthenticatedCategoriesRoute._addFileChildren(
    AuthenticatedCategoriesRouteChildren,
  )

interface AuthenticatedLeaderboardRouteChildren {
  AuthenticatedLeaderboardArchiveRoute: typeof AuthenticatedLeaderboardArchiveRoute
}

const AuthenticatedLeaderboardRouteChildren: AuthenticatedLeaderboardRouteChildren =
  {
    AuthenticatedLeaderboardArchiveRoute: AuthenticatedLeaderboardArchiveRoute,
  }

const AuthenticatedLeaderboardRouteWithChildren =
  AuthenticatedLeaderboardRoute._addFileChildren(
    AuthenticatedLeaderboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRouteWithChildren
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedSuggestRoute: typeof AuthenticatedSuggestRoute
  AuthenticatedTrendingRoute: typeof AuthenticatedTrendingRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminRecommendationsRoute: typeof AuthenticatedAdminRecommendationsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedCreatorsIdRoute: typeof AuthenticatedCreatorsIdRoute
  AuthenticatedMeTabRoute: typeof AuthenticatedMeTabRoute
  AuthenticatedVIdRoute: typeof AuthenticatedVIdRoute
  AuthenticatedCreatorsIndexRoute: typeof AuthenticatedCreatorsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRouteWithChildren,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedSuggestRoute: AuthenticatedSuggestRoute,
  AuthenticatedTrendingRoute: AuthenticatedTrendingRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminRecommendationsRoute:
    AuthenticatedAdminRecommendationsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedCreatorsIdRoute: AuthenticatedCreatorsIdRoute,
  AuthenticatedMeTabRoute: AuthenticatedMeTabRoute,
  AuthenticatedVIdRoute: AuthenticatedVIdRoute,
  AuthenticatedCreatorsIndexRoute: AuthenticatedCreatorsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronLeaderboardRoute: ApiPublicCronLeaderboardRoute,
  ApiPublicCronRefreshMvsRoute: ApiPublicCronRefreshMvsRoute,
  ApiPublicCronSessionExpiryWarnRoute: ApiPublicCronSessionExpiryWarnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
